2025-09-27 23:15:10,454 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:15:20,693 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:15:30,690 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:15:40,683 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:15:50,710 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:16:00,681 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:16:10,694 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:16:20,685 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:16:30,680 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:16:40,688 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:16:50,685 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:17:00,699 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:17:10,679 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:17:20,675 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:17:30,696 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:17:40,674 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:17:50,687 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:18:00,688 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:18:10,667 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:18:20,678 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:18:30,685 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:18:40,727 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:18:50,705 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:19:00,689 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:19:10,708 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:19:20,673 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:19:30,673 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:19:40,679 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:19:50,689 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:20:00,685 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:20:10,693 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:20:20,694 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
2025-09-27 23:20:30,700 - root - ERROR - Application error: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
Traceback (most recent call last):
  File "main.py", line 44, in _run
    new_data = self.fetcher()
  File "main.py", line 157, in _stock_fetch
    res = Stock().fund_etf(CONFIG['etf'][0])
  File "stock.py", line 11, in fund_etf
    res_df = adata.fund.market.get_market_etf_current(fund_code=code)
  File "adata\fund\market\etf_market.py", line 53, in get_market_etf_current
  File "adata\fund\market\etf_market_ths.py", line 133, in get_market_etf_current_ths
  File "adata\common\base\base_ths.py", line 37, in _get_text
  File "adata\common\utils\cookie.py", line 15, in ths_cookie
  File "py_mini_racer\py_mini_racer.py", line 178, in __init__
  File "py_mini_racer\py_mini_racer.py", line 125, in _build_ext_handle
RuntimeError: Native library not available at C:\Users\ADMINI~1\AppData\Local\Temp\_MEI192842\mini_racer.dll
